const fs = require('fs-extra');
const path = require('path');
const moment = require('moment');
const { v4: uuidv4 } = require('uuid');
const config = require('../config');

class FileGenerator {
  constructor() {
    this.outputDir = config.outputDir;
    this.ensureOutputDirectory();
  }

  /**
   * Ensure output directory exists
   */
  async ensureOutputDirectory() {
    try {
      await fs.ensureDir(this.outputDir);
      console.log(`Output directory ensured: ${this.outputDir}`);
    } catch (error) {
      console.error(`Failed to create output directory: ${error.message}`);
    }
  }

  /**
   * Generate a file with content
   */
  async generateFile(mode, topic, content, style = null) {
    try {
      // Sanitize filename
      const sanitizedTopic = this.sanitizeFilename(topic);
      const timestamp = moment().format('YYYYMMDD_HHmmss');
      const uniqueId = uuidv4().substring(0, 8);
      
      // Determine filename based on mode
      let filename;
      if (mode === 'script' || mode === 'shorts') {
        filename = `${mode}_${sanitizedTopic}_${timestamp}_${uniqueId}.txt`;
      } else {
        filename = `${mode}_${sanitizedTopic}_${timestamp}.txt`;
      }
      
      // Limit filename length
      if (filename.length > 100) {
        filename = `${mode}_${timestamp}_${uniqueId}.txt`;
      }
      
      const filePath = path.join(this.outputDir, filename);
      
      // Prepare file content with metadata
      const fileContent = this.prepareFileContent(mode, topic, content, style, timestamp);
      
      // Write file with UTF-8 encoding (important for Hindi/Unicode)
      await fs.writeFile(filePath, fileContent, 'utf8');
      
      console.log(`File generated: ${filePath}`);
      return filePath;
    } catch (error) {
      console.error(`Error generating file: ${error.message}`);
      throw error;
    }
  }

  /**
   * Prepare file content with metadata
   */
  prepareFileContent(mode, topic, content, style, timestamp) {
    const modeConfig = config.modes[mode.toLowerCase()];
    const modeName = modeConfig ? modeConfig.name : mode.toUpperCase();
    
    let fileContent = '';
    
    // Header with metadata
    fileContent += `========================================\n`;
    fileContent += `CONTENT GENERATOR BOT - ${modeName}\n`;
    fileContent += `========================================\n`;
    fileContent += `Topic: ${topic}\n`;
    fileContent += `Mode: ${modeName}\n`;
    if (style) {
      fileContent += `Style: ${style}\n`;
    }
    fileContent += `Generated: ${moment(timestamp, 'YYYYMMDD_HHmmss').format('YYYY-MM-DD HH:mm:ss')}\n`;
    fileContent += `Timestamp: ${timestamp}\n`;
    fileContent += `Encoding: UTF-8\n`;
    fileContent += `========================================\n\n`;
    
    // Main content
    fileContent += content;
    
    // Footer
    fileContent += `\n\n========================================\n`;
    fileContent += `END OF CONTENT\n`;
    fileContent += `Generated by Telegram Content Creator Bot\n`;
    fileContent += `========================================\n`;
    
    return fileContent;
  }

  /**
   * Sanitize filename to remove invalid characters
   */
  sanitizeFilename(filename) {
    return filename
      .replace(/[<>:"/\\|?*]/g, '_') // Replace invalid filename characters
      .replace(/\s+/g, '_')          // Replace spaces with underscores
      .substring(0, 50)              // Limit length
      .trim();
  }

  /**
   * Clean up old files (optional maintenance)
   */
  async cleanupOldFiles(maxAgeHours = 24) {
    try {
      const files = await fs.readdir(this.outputDir);
      const now = moment();
      
      for (const file of files) {
        const filePath = path.join(this.outputDir, file);
        const stats = await fs.stat(filePath);
        const fileAge = moment.duration(now.diff(moment(stats.mtime)));
        
        if (fileAge.asHours() > maxAgeHours) {
          await fs.unlink(filePath);
          console.log(`Cleaned up old file: ${file}`);
        }
      }
    } catch (error) {
      console.error(`Error cleaning up files: ${error.message}`);
    }
  }

  /**
   * Get file statistics
   */
  async getFileStats() {
    try {
      const files = await fs.readdir(this.outputDir);
      const stats = {
        totalFiles: files.length,
        totalSize: 0,
        byMode: {}
      };
      
      for (const file of files) {
        const filePath = path.join(this.outputDir, file);
        const fileStat = await fs.stat(filePath);
        stats.totalSize += fileStat.size;
        
        // Categorize by mode
        const modeMatch = file.match(/^(script|shorts|title|thumbnail|seo|idea)_/);
        if (modeMatch) {
          const mode = modeMatch[1];
          stats.byMode[mode] = (stats.byMode[mode] || 0) + 1;
        }
      }
      
      // Convert size to human readable format
      stats.totalSizeReadable = this.formatFileSize(stats.totalSize);
      
      return stats;
    } catch (error) {
      console.error(`Error getting file stats: ${error.message}`);
      return null;
    }
  }

  /**
   * Format file size in human readable format
   */
  formatFileSize(bytes) {
    if (bytes === 0) return '0 Bytes';
    
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  }

  /**
   * Read file content
   */
  async readFile(filePath) {
    try {
      return await fs.readFile(filePath, 'utf8');
    } catch (error) {
      console.error(`Error reading file: ${error.message}`);
      throw error;
    }
  }

  /**
   * Delete file
   */
  async deleteFile(filePath) {
    try {
      await fs.unlink(filePath);
      console.log(`File deleted: ${filePath}`);
      return true;
    } catch (error) {
      console.error(`Error deleting file: ${error.message}`);
      return false;
    }
  }
}

module.exports = FileGenerator;