const fs = require('fs-extra');
const path = require('path');
const config = require('../config');

class CommandHandler {
  constructor(botService) {
    this.botService = botService;
  }

  /**
   * Handle /script command
   */
  async handleScript(ctx) {
    await this.handleContentGeneration(ctx, 'script');
  }

  /**
   * Handle /shorts command
   */
  async handleShorts(ctx) {
    await this.handleContentGeneration(ctx, 'shorts');
  }

  /**
   * Handle /title command
   */
  async handleTitle(ctx) {
    await this.handleContentGeneration(ctx, 'title');
  }

  /**
   * Handle /thumbnail command
   */
  async handleThumbnail(ctx) {
    await this.handleContentGeneration(ctx, 'thumbnail');
  }

  /**
   * Handle /seo command
   */
  async handleSeo(ctx) {
    await this.handleContentGeneration(ctx, 'seo');
  }

  /**
   * Handle /idea command
   */
  async handleIdea(ctx) {
    try {
      await ctx.reply('💡 Generating content idea...');

      const userId = ctx.from.id;
      const idea = await this.botService.getContentIdea();

      const message = `🎯 **Content Idea:** ${idea.idea}\n\n📝 **Why it works:** ${idea.elaboration}\n\n💡 **Suggested formats:**\n• YouTube video essay\n• Instagram carousel\n• LinkedIn article\n• TikTok/Reels series\n• Podcast episode`;

      await ctx.reply(message, { parse_mode: 'Markdown' });
    } catch (error) {
      console.error('Error handling idea command:', error);
      await ctx.reply('❌ Failed to generate idea. Please try again.');
    }
  }

  /**
   * Generic content generation handler
   */
  async handleContentGeneration(ctx, mode) {
    try {
      const userId = ctx.from.id;
      const text = ctx.message.text;
      
      // Parse command
      const { topic, style } = this.botService.parseCommand(text, mode);
      
      if (!topic) {
        await ctx.reply(`Please provide a topic. Example: /${mode} artificial intelligence`);
        return;
      }

      // Send processing message
      const processingMessage = await ctx.reply(
        `⏳ Generating ${mode} content for "${topic}"${style ? ` (${style} style)` : ''}...`
      );

      // Generate content
      const result = await this.botService.generateContent(mode, topic, style, userId.toString());

      if (!result.success) {
        await ctx.editMessageText(
          `❌ Failed to generate content: ${result.error}`,
          { chat_id: processingMessage.chat.id, message_id: processingMessage.message_id }
        );
        return;
      }

      // Edit processing message to show completion
      await ctx.editMessageText(
        `✅ ${mode.toUpperCase()} generated successfully for "${topic}"!`,
        { chat_id: processingMessage.chat.id, message_id: processingMessage.message_id }
      );

      // Send the content
      if (result.filePath) {
        // Send as file for script/shorts
        await this.sendAsFile(ctx, result);
      } else {
        // Send as text message for other modes
        await this.sendAsText(ctx, result);
      }

    } catch (error) {
      console.error(`Error handling ${mode} command:`, error);
      await ctx.reply(`❌ An error occurred while processing your ${mode} request. Please try again.`);
    }
  }

  /**
   * Send content as text message
   */
  async sendAsText(ctx, result) {
    const { mode, topic, content, style } = result;
    
    let header = `📋 **${mode} for "${topic}"**`;
    if (style) {
      header += ` (${style} style)`;
    }
    
    // Telegram has a 4096 character limit per message
    if (content.length <= 4000) {
      await ctx.reply(`${header}\n\n${content}`, { parse_mode: 'Markdown' });
    } else {
      // Split into multiple messages
      const chunks = this.splitMessage(content, 4000);
      
      await ctx.reply(`${header}\n\n${chunks[0]}`, { parse_mode: 'Markdown' });
      
      for (let i = 1; i < chunks.length; i++) {
        await ctx.reply(chunks[i], { parse_mode: 'Markdown' });
      }
    }
  }

  /**
   * Send content as downloadable file
   */
  async sendAsFile(ctx, result) {
    const { mode, topic, filePath, style } = result;
    
    try {
      // Read the file
      const fileBuffer = await fs.readFile(filePath);
      const filename = path.basename(filePath);
      
      // Send document
      await ctx.replyWithDocument({
        source: fileBuffer,
        filename: filename
      }, {
        caption: `📄 ${mode.toUpperCase()} for "${topic}"${style ? ` (${style} style)` : ''}\n\nGenerated by Content Creator Bot`
      });
      
      // Also send a preview
      const preview = await this.getFilePreview(filePath);
      if (preview) {
        await ctx.reply(`📝 **Preview:**\n\n${preview}`, { parse_mode: 'Markdown' });
      }
      
    } catch (error) {
      console.error('Error sending file:', error);
      // Fallback to text
      await this.sendAsText(ctx, result);
    }
  }

  /**
   * Get first few lines of file for preview
   */
  async getFilePreview(filePath, maxLines = 10) {
    try {
      const content = await fs.readFile(filePath, 'utf8');
      const lines = content.split('\n').slice(0, maxLines);
      return lines.join('\n');
    } catch (error) {
      return null;
    }
  }

  /**
   * Split message into chunks respecting character limit
   */
  splitMessage(text, maxLength) {
    const chunks = [];
    let currentChunk = '';
    
    const lines = text.split('\n');
    
    for (const line of lines) {
      if (currentChunk.length + line.length + 1 <= maxLength) {
        currentChunk += (currentChunk ? '\n' : '') + line;
      } else {
        if (currentChunk) {
          chunks.push(currentChunk);
        }
        currentChunk = line;
      }
    }
    
    if (currentChunk) {
      chunks.push(currentChunk);
    }
    
    return chunks;
  }
}

module.exports = CommandHandler;